ahoyapi: v2
commands:
  link-bashrc:
    usage: Links bashrc to the one in this repository.
    cmd: |
      if [ -L ~/.bashrc ]; then
        echo '.bashrc is already symlinked'
        exit 0
      elif [ -e ~/.bashrc ]; then
        mv ~/.bashrc ~/.bashrc.orig
        echo 'Original .bashrc moved to ~/.bashrc.orig'
      fi
      ln -s $(pwd)/bashrc ~/.bashrc
  install-packages:
    usage: Install regularly-used homebrew packages.
    cmd: |
      brew install dnsmasq httpd mariadb memcached
      brew tap homebrew/cask
      brew cask install gimp skitch visual-studio-code
  set-wallpaper:
    usage: Replaces the Deloitte wallpaper by the Mac one.
    cmd: ./set-wallpaper.sh
  vsc-settings:
    usage: Links the Visual Studio Code settings from this repository to the user settings file.
    cmd: ./vscode-setup.sh
  vsc-save-extensions-list:
    usage: Saves a list of extensions installed globally. Don't forget to commit afterwards.
    cmd: code --list-extensions > vscode-extensions
