ahoyapi: v2
commands:
  set-wallpaper:
    usage: Replaces the Deloitte wallpaper by the Mac one.
    cmd: ./set-wallpaper.sh
  vsc-settings:
    usage: Links the Visual Studio Code settings from this repository to the user settings file.
    cmd: ./vscode-setup.sh
  vsc-save-extensions-list:
    usage: Saves a list of extensions installed globally. Don't forget to commit afterwards.
    cmd: code --list-extensions > vscode-extensions
