package_update: true
package_upgrade: true

packages:
  - php7.4-cli
  - python3-pip

# The rendered script for runcmd is at /var/lib/cloud/instance/scripts/runcmd.
runcmd:
  # Remove snaps.
  - snap remove --purge lxd &&
    snap remove --purge core20 &&
    snap remove --purge snapd &&
    rm -rf /var/cache/snapd/ &&
    apt-get autoremove --purge snapd --yes && apt-mark hold snapd

  # Install docker.
  - curl -fsSL https://get.docker.com | sh && usermod -aG docker ubuntu &&
    pip install docker-compose

  - export BIN_ARCH=arm64 &&
    export PYGMY_VERSION=0.8.0 &&
    export GO_VERSION=1.17.6 &&
    export AHOY_VERSION=2.1.0

  # Install pygmy.
  - curl -LO https://github.com/pygmystack/pygmy/releases/download/v${PYGMY_VERSION}/pygmy-go_${PYGMY_VERSION}_linux_${BIN_ARCH}.tar.gz &&
    tar -xf pygmy-go_${PYGMY_VERSION}_linux_${BIN_ARCH}.tar.gz pygmy-go &&
    mv pygmy-go /usr/local/bin/pygmy &&
    rm pygmy-go_${PYGMY_VERSION}_linux_${BIN_ARCH}.tar.gz

  # Install ahoy.
  - curl -LO https://github.com/ocean/ahoy/releases/download/${AHOY_VERSION}/ahoy_linux_${BIN_ARCH}.tar.gz &&
    tar -xf ahoy_linux_${BIN_ARCH}.tar.gz && mv ahoy /usr/local/bin/ahoy

  # Install go.
  - curl -LO https://go.dev/dl/go${GO_VERSION}.linux-${BIN_ARCH}.tar.gz &&
    sudo tar -C /usr/local -xzf go${GO_VERSION}.linux-${BIN_ARCH}.tar.gz &&
    echo 'export PATH=$PATH:/usr/local/go/bin' | sudo tee /etc/profile.d/go.sh > /dev/null &&
    rm go${GO_VERSION}.linux-${BIN_ARCH}.tar.gz

  # Import ssh key from github for user ubuntu.
  - sudo -H -u ubuntu bash -c 'ssh-import-id-gh yusufhm' &&
    sudo -H -u ubuntu bash -c 'mkdir -p ~/sites ~/projects ~/go/src'

power_state:
  mode: reboot
  timeout: 60
