#!/usr/bin/env bash

# Strict bash mode.
set -o errtrace
set -o errexit
set -o nounset

wallpaper_dir=/private/var/wallpaper
if [ -L "${wallpaper_dir}/dtta.jpg" ]; then
    echo "Wallpaper already replaced."
    exit 0
fi

# This would have been generated by imagemagick.
#   - brew install imagemagick
#   - magick convert /System/Library/Desktop\ Pictures/Catalina.heic \
#       ~/Catalina.jpg
mac_picture_name=Catalina.jpg
mac_picture_path=~/${mac_picture_name}
if [ ! -f "${mac_picture_path}" ]; then
    echo "Mac picture not found!"
    exit 1
fi

if [ ! -d "${wallpaper_dir}" ]; then
    echo "Wallpaper dir does not exist!"
    exit 1
fi

sudo cp "${mac_picture_path}" ${wallpaper_dir}/${mac_picture_name}
sudo mv ${wallpaper_dir}/dtta.jpg ${wallpaper_dir}/dtta-deloitte.jpg
sudo ln -s "${wallpaper_dir}/${mac_picture_name}" ${wallpaper_dir}/dtta.jpg
killall -KILL Dock
echo "Successfully replaced wallpaper after keeping backup at ${wallpaper_dir}/dtta-deloitte.jpg."
