services:
  box:
    container_name: kasmweb_box
    build:
      context: .
      args:
        KASMWEB_VERSION: ${KASMWEB_VERSION:-1.15.0}
    image: kasmweb_box
    environment:
      VNC_PW: ${VNC_PW:-password}
    ports:
      - "6901:6901"
    shm_size: 512m
