ahoyapi: v2
commands:
  link-bashrc:
    usage: Links bashrc to the one in this repository.
    cmd: |
      if [ -L ~/.bashrc ]; then
        echo '.bashrc is already symlinked'
        exit 0
      elif [ -e ~/.bashrc ]; then
        mv ~/.bashrc ~/.bashrc.orig
        echo 'Original .bashrc moved to ~/.bashrc.orig'
      fi
      ln -s $(pwd)/bashrc ~/.bashrc
  link-zshrc:
    usage: Links zshrc to the one in this repository.
    cmd: |
      if [ -L ~/.zshrc ]; then
        echo '.zshrc is already symlinked'
        exit 0
      elif [ -e ~/.zshrc ]; then
        mv ~/.zshrc ~/.zshrc.orig
        echo 'Original .zshrc moved to ~/.zshrc.orig'
      fi
      ln -s $(pwd)/zshrc ~/.zshrc
  install-packages:
    usage: Install regularly-used homebrew packages.
    cmd: |
      brew install libiconv openldap
      brew tap homebrew/cask
      brew cask install gimp skitch visual-studio-code
  install-lamp:
    usage: Install AMP
    cmd: brew install dnsmasq httpd mariadb php@7.3
  install-memcache:
    usage: Install memcache (with dependencies)
    cmd: |
      brew install memcached libmemcached zlib
      echo 'Installing PECL memcached; it\'s safe to just press enter for the prompts'
      pecl install memcached
  set-wallpaper:
    usage: Replaces the Deloitte wallpaper by the Mac one.
    cmd: ./set-wallpaper.sh
  vsc-settings:
    usage: Links the Visual Studio Code settings from this repository to the user settings file.
    cmd: ./vscode-setup.sh
  vsc-save-extensions-list:
    usage: Saves a list of extensions installed globally. Don't forget to commit afterwards.
    cmd: code --list-extensions > vscode-extensions
  setup-docksal-dns:
    usage: Sets up DNS for docksal.
    cmd: |
      cd ../docksal-dnsmasq && docker-compose up -d && cd mac
      # Do not set symlink name as docksal.site because `fin system reset` deletes that file.
      sudo ln -s $(pwd)/docksal-resolver /etc/resolver/dev-machine
