- name: Download docker keyring
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444'

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: true
  vars:
    arch: "{{ (ansible_architecture == 'aarch64') | ternary('arm64', 'amd64') }}"

- name: Install docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Add the user to the docker group
  ansible.builtin.user:
    name: "{{ vm_user }}"
    groups: docker
    append: true
  notify: reboot
